### ISSUE TITLE
RStudio send command not working

### ISSUE THREAD

**Issue by bwiernik** [randy3k/SendREPL#13]
I am running RStudio on macOS Sierra with SendREPL in Sublime Text 3. When I set SendREPL to use R, the Send command works as expected. However, nothing happens I try to use the Send command with SendREPL set to RStudio. Do I have something set up wrong, or is this a bug in the script for RStudio?

Thanks!

**Comment by randy3k** [comment]
What version of RStudio are you using? Try updating it to the latest version.

**Comment by bwiernik** [comment]
Current version: 0.99.467

--
Brenton Wiernik
University of Minnesota




On Tue, Sep 13, 2016 at 12:23 PM -0500, "Randy Lai" <notifications@github.com> wrote:












What version of RStudio are you using? Try updating it to the latest version.

**Comment by randy3k** [comment]
You need at least v0.99.903.

**Comment by bwiernik** [comment]
Thanks. For some reason, RStudio was telling me I had the current version. Sorry for the hassle.
