### ISSUE TITLE
Text send partially with tmux

### ISSUE THREAD

**Issue by yzhao0527** [randy3k/SendREPL#14]
I might have asked this question before.  Maybe I should spend sometime and figure out what went wrong my self.

My environment:  Windows 7 Enterprise + MobaXterm 8.4 + tmux 2.2 + R 3.3.0.

Even without highlighting a block, usually SendREPL is able to recognized an R block and sends the entire block from SublimeText tmux.  However, sometimes, only the start of the block is sent over.  Below is the exact text sent over to the terminal even though the code itself is complete and free of error:

    res <- foreach(block=splitted, .packages='data.table') %dopar% {
        dd <- block$Date[1]
        yy <- year(dd)
        ymd8 <- strftime(dd, '%Y%m%d')
        
        x <

the last line is supposed to be 

    x <- block[, list(...), by=...]

Unfortunately, I don't quite understand what causes this,  I cannot provide a more concrete example that reproduces this error.

I am wondering how exactly you send text to the terminal? through system copy/paste or some other mechanism.  I would be willing to spend sometime this weekend on this.

**Comment by randy3k** [comment]
For tmux, SendREPL splits the code into chunks of 200 and [send each chunk](https://github.com/randy3k/SendREPL/blob/e3b8e39b5f72f23c51169c9fe20bab57466c4850/tmux/__init__.py#L17) to tmux via tmux command.

**Comment by yzhao0527** [comment]
That could be the reason, I removed some of the firm's prop functions from my code.

**Comment by randy3k** [comment]
tmux on mac and linux does not seem to be affected, perhaps is a problem of windows tmux?

**Comment by yzhao0527** [comment]
The problem is it usually works even with large blocks, I say the odd is 1:20 that SendREPL only sends the first few lines.

**Comment by randy3k** [comment]
perhaps some latency betwee chunks will fix the issue

**Comment by yzhao0527** [comment]
Hopefully the code below is reproducible so you know what I am talking about:

Rscript:

```
for (i in 1:100) {
    x <- 123456789
    x <- 123456789
    x <- 123456789
    x <- 123456789
    x <- 123456789
    x <- 123456789
    x <- 123456789
    x <- 123
    x <- 123456781
    x <- 123456789
    x <- 123456789
    x <- 123456789
    x <- 123456789
    x <- 123456789
    x <- 123456789
    x <- 123456789
    x <- 123456789
    x <- 123456789
    x <- 123456789
    x <- 123456789
    x <- 123456789
    x <- 123456789
    x <- 123456789
    x <- 123456789
    x <- 123456789
    x <- 123456789
    x <- 123456789
    x <- 123456789
    x <- 123456789
    x <- 123456789
}
```

what gets sent to tmux:

```
> for (i in 1:100) {
+     x <- 123456789
+     x <- 123456789
+     x <- 123456789
+     x <- 123456789
+     x <- 123456789
+     x <- 123456789
+     x <- 123456789
+     x <- 123
+     x <- 123456781
+     x <- 123456789
+     x <- 123456789
+     x <- 123456789
+     x <- 123456789
+     x <- 123456789
+     x <- 123456789
+     x <- 123456789
+     x <- 123456789
+     x <- 123456789
+     x <- 123456789
+     x <- 123456789
+     x <
```

This only happens with the assignment arrow `<-`, I suspect only when `<` and `-` are at specific positions the text won't be sent successfully.

**Comment by randy3k** [comment]
This reminds me of a fix earlier https://github.com/randy3k/SendREPL/commit/6414fe481458be6eb681ee4ddaf14e06d1f460c7

I have assumed that the above has fixed the issue, but apparently, it doesn't.

Is there any error messages in your console?

**Comment by yzhao0527** [comment]
Nan, the console just hang there waiting for more text to be paste over to complete that for-loop block.

**Comment by randy3k** [comment]
I meant the sublime console (ctrl+`)

**Comment by yzhao0527** [comment]
I see the error message is:

Traceback (most recent call last):
  File "/xxx/apps/sublime_text_3/sublime_plugin.py", line 818, in run_
    return self.run(edit)
  File "commands in /home/xxx/.config/sublime-text-3/Installed Packages/SendTextPlus.sublime-package", line 81, in run
  File "textsender in /home/xxx/.config/sublime-text-3/Installed Packages/SendTextPlus.sublime-package", line 36, in send_text
  File "textsender in /home/xxx/.config/sublime-text-3/Installed Packages/SendTextPlus.sublime-package", line 241, in _dispatch_tmux
  File "./python3.3/subprocess.py", line 547, in check_call
subprocess.CalledProcessError: Command '['tmux', 'set-buffer', '- 123456789\n    x <- 123456789\n    x <- 123456789\n    x <- 123456789\n    x <- 123456789\n    x <- 123456789\n    x <- 123456789\n    x <- 123456789\n    x <- 123456789\n    x <- 123456789\n}\n']' returned non-zero exit status 1

**Comment by randy3k** [comment]
It seems that you are not using the latest SendREPL?

**Comment by yzhao0527** [comment]
oops, I reinstalled SendREPL and now it works fine.
