### ISSUE TITLE
SendREPL not working on Windows 7 Pro

### ISSUE THREAD

**Issue by intheravine** [randy3k/SendREPL#17]
I'm running ST 3 (build 3125) and R Box and SendREPL. I recently cleaned up my ST 3 by refreshing my packages with Package Control. Afterword, sending my R code to the R REPL stopped working. I've tried uninstalling and reinstalling both R Box and SendREPL and have not had any luck sending code to the R REPL. In addition, while the R Box menu item appears on the menu bar only one item is NOT greyed out - Clear Workspace - all other choices are greyed out. Any help getting SendREPL working most appreciated.

**Comment by randy3k** [comment]
Did you try to restart Sublime Text? It sounds like you don't have a working installation of `SendREPL`.

**Comment by intheravine** [comment]
Yes. I've restarted ST multiple times. I've uninstalled both RBox and SendREPL and reinstalled - and restarted ST - same result - R-Box menu with only Clear Workspace available and not able to send anything to REPL R.

**Comment by randy3k** [comment]
If you clear all the existing user files, after installing SendREPL, there should be a pop out message asking you to restart. Did you get that?

**Comment by intheravine** [comment]
Can you clarify "clear all the existing user files"? I did not get any pop out message after installing SendREPL.

**Comment by randy3k** [comment]
I meant removing all the files under the `Sublime Text 3` folder. It can be opened by using the `Preferences: Browse Packages` command.

**Comment by intheravine** [comment]
I removed all files in the location pointed to by Preferences: Browse Packages. I reinstalled SendREPL and still have the same result.

**Comment by randy3k** [comment]
No only the files under `Packages`, but all the files under `Sublime Text 3`. You could just simply remove the directory `Sublime Text 3`.

**Comment by intheravine** [comment]
Wow - I guess I have to reinstall all my packages and re-do my custom settings - ok - SendREPL is working now - thanks.

**Comment by randy3k** [comment]
It was likely caused by an incomplete installation of SendREPL.
