### ISSUE TITLE
Python SyntaxError

### ISSUE THREAD

**Issue by altre** [randy3k/SendREPL#24]
When sending a python block with auto_expand_line to terminal in macos, I receive the following error:

`  --`
`    ^`
`SyntaxError: invalid syntax`

It looks like it's sending '--' at the end of the string.
Any ideas?

**Comment by randy3k** [comment]
iPython console is assumed, would you ensure that you are using iPython?

**Comment by altre** [comment]
I was not using iPython, and that solved the problem. Thank you very much!
However, I sometimes ssh into servers which do not have iPython installed and where I do not have the rights to install it. Do you think it might be interesting to support the standard python console, as well?
But since it solved my immediate problem, I'll quickly close the issue so it doesn't annoy you.
