### ISSUE TITLE
FR: For R syntax, capture R Pipe (%>%) similar to braces ({ })

### ISSUE THREAD

**Issue by rsaporta** [randy3k/SendREPL#29]
In an `R` file, if a line ends in a pipe, when executing, the subsequent line should be captured as well. 

For example all of the following should be executed as one block

```R
bn2 <- babynames %>%
    filter(name %>% substr(1, 3) %>% equals("Ste")) %>%
    group_by(year, sex) %>%
    summarize(total = sum(n)) %>%
    qplot(year, total, color = sex, data = ., geom = "line") %>%
    add(ggtitle('Names starting with "Ste"')) %T>%
    print
```

These come from the [magrittr package](https://github.com/tidyverse/magrittr)

```R
%>%
%<>%
%T>%
%$%
```

**Comment by rsaporta** [comment]
Just tested it.  Works brilliantly, thanks randy

**Comment by puterleat** [comment]
Has this been pushed to package control yet?

**Comment by randy3k** [comment]
Yes, it is.

**Comment by puterleat** [comment]
OK... I've just cross-checked my installed package and it matches master in GitHub, but I'm not getting the desired behaviour. If my cursor is in the middle of the data_frame call then the second line is not captured and sent.

```
data_frame('a'=1:10) %>% 
  mean(a)
```

I'm on the latest OS X, Sublime stable build 3126.

**Comment by randy3k** [comment]
Are you using the R Extended syntax of R-Box?
