### ISSUE TITLE
[bug] `%cpaste -q` inserted into multi-line string literals when sent line-by-line

### ISSUE THREAD

**Issue by bobcolner** [randy3k/SendREPL#3]
When I send this code:
```
source = '''
def testing(wow: int) -> str:
    wow.
'''
```
 to the ipython repl via sendrepl (sent as individual lines) this is the results:

```
In [40]: print(source)

%cpaste -q
def testing(wow: int) -> str:
    wow.
--
```

The `%cpaste -q` code in incorrectly included in my string variable. Note this is not the case if the entire code block is highlighted and then sent to ipython via sendrepl:

```
In [42]: print(source)

def testing(wow: int) -> str:
    wow.
```

**Comment by randy3k** [comment]
Ah...the cursor should not advance inside strings..
