### ISSUE TITLE
Installation Failed

### ISSUE THREAD

**Issue by yueatwork** [randy3k/SendREPL#7]
Hi,

I am having trouble installing SendREPL.  I recently upgraded my Sublime3 to build 3114 and need to reinstall all packages.  However, after installing SendREPL via Package Control,, I don't see it showing up in the menu bar nor in Preferences -> Package Setting. 

I got the following message during installation:

    Package Control: Removed old directory python-pywin32
    Package Control: Skipping automatic upgrade, last run at 2016-08-01 08:48:08, next run at 2016-08-01 09:48:08 or after
    ignored packages updated to: ["SendREPL", "Vintage"]
    reloading settings Packages/User/Package Control.sublime-settings
    warning: mnemonic r not found in menu caption R-Box
    reloading settings Packages/User/Preferences.sublime-settings
    warning: mnemonic r not found in menu caption R-Box
    Package Control: The dependency python-pywin32 is not currently installed; installing
    python-pywin32: Added 'win32com'
    python-pywin32: Added 'win32'
    python-pywin32: Added 'win32/lib'
    python-pywin32: Added 'win32comext'
    Package Control: The dependency python-pywin32 has successfully been installed or updated
    reloading settings Packages/User/Package Control.sublime-settings
    warning: mnemonic r not found in menu caption R-Box
    ignored packages updated to: ["Vintage"]
    reloading plugin SendREPL.choose_repl
    reloading plugin SendREPL.clipboard
    reloading plugin SendREPL.send_repl
    reloading plugin SendREPL.settings
    reloading plugin SendREPL.text_getter
    reloading plugin SendREPL.text_sender
    warning: mnemonic r not found in menu caption R-Box
    warning: mnemonic r not found in menu caption R-Box
    reloading settings Packages/User/Package Control.sublime-settings
    reloading settings Packages/User/Preferences.sublime-settings
    warning: mnemonic r not found in menu caption R-Box
    reloading settings Packages/User/Preferences.sublime-settings
    warning: mnemonic r not found in menu caption R-Box

Is there something wrong with my installation?

**Comment by randy3k** [comment]
I see that you have disabled `SendREPL`.

**Comment by yueatwork** [comment]
I reinstalled Sublime and this get fixed.

**Comment by randy3k** [comment]
great.

**Comment by yzhao0527** [comment]
It seems I got the same problem again.  In a newly installed Sublime3, I installed R-box and SendREPL. However, when hitting Ctrl+Enter, nothing happened:

When I set program to R in SendREPL, I got the following msg:

    reloading settings Packages/User/SendREPL.sublime-settings
    warning: mnemonic r not found in menu caption R-Box

My R is installed at:

    C:\apps\MRO-3.3.1\bin\x64

I didn't set any user configuration for either R-box or SendREPL.

**Comment by randy3k** [comment]
You may need to use the choose REPL program option to select a program.
