### ISSUE TITLE
Julia REPL on windows

### ISSUE THREAD

**Issue by PaulSoderlind** [randy3k/SendREPL#8]
Hi,
thanks for the nice program. Here are two observations:

(1) I need to start sublime_text from cmder to make SendREPL work with julia (also started from cmder). (Probably related to paths, or?)

(2)  in Julia - Source File.sublime-build, I needed to change to 
    "cmd": "include(\"$file_name\")",
since Julia does not accept windows paths with backslash (like e:\stuff\LongCalc.jl)

/Paul S

**Comment by randy3k** [comment]
1. You have to either specify the path to `ConEmuC.exe` in PATH variable or [register](https://github.com/cmderdev/cmder#shortcut-to-open-cmder-in-a-chosen-folder) Cmder.

2. It is a bug and will be fixed.
