### ISSUE TITLE
send_repl doesn't like tabs in R code

### ISSUE THREAD

**Issue by ultinomics** [randy3k/SendREPL#9]
I generally have the ST3 option `"translate_tabs_to_spaces": true` but recently changed it to `false` and noticed that, with `send_repl`, I always get a warning ping when I send the code to the Terminal. It still runs, but it's a bit annoying. 

This was not an issue with the old `send_text_plus` or when code is written under `"translate_tabs_to_spaces": true`. So, it's gotta be something with tabs.

It's best shown in a [video](https://www.dropbox.com/s/ag46bzx7w4p4iw7/send_repl_tab_issue.mov). But in short, when there are tabs present in code, it runs, but causes the "error" sound and window bounce in terminal. Not an issue when tabs are converted to spaces.

**Comment by randy3k** [comment]
What prog are you sending the code to?

**Comment by randy3k** [comment]
I know what is causing the issue, will fix it soon

**Comment by ultinomics** [comment]
Nice! I tried looking at the source code but my applescript is nonexistent.

Thanks dude!

**Comment by randy3k** [comment]
Fixed in 26e8e7d98d4bdfb1225ab0af1ee2ce7d2e645aa8 and v0.1.5 has released.
